services:
  node1:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MY_ID=A
      - MY_HOSTNAME=node1
    networks:
      - mynetwork

  node2:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MY_ID=B
      - MY_HOSTNAME=node2
    networks:
      - mynetwork

  node3:
    build: .
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MY_ID=C
      - MY_HOSTNAME=node3
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
